# Generated by Django 4.2.15 on 2025-11-12 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gmail_app", "0003_aicontext_temporalrule_emailintent_airesponse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "provider",
                    models.CharField(
                        choices=[("gmail", "Gmail"), ("outlook", "Outlook/Office 365")],
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="email",
            name="gmail_id",
        ),
        migrations.AddField(
            model_name="email",
            name="provider_id",
            field=models.CharField(db_index=True, default="temp", max_length=255),
        ),
        migrations.AlterField(
            model_name="email",
            name="gmail_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="gmail_app.gmailaccount",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="received_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="thread_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["-received_date"], name="gmail_app_e_receive_4f1a99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["email_account", "provider_id"],
                name="gmail_app_e_email_a_c87bb8_idx",
            ),
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="email_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="gmail_app.emailaccount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailaccount",
            unique_together={("user", "email", "provider")},
        ),
    ]
