# Generated by Django 4.2.15 on 2025-11-12 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmail_app', '0004_emailaccount_remove_email_gmail_id_email_provider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalrule',
            name='ai_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporal_rules', to='gmail_app.aicontext'),
        ),
        migrations.CreateModel(
            name='AIRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Role name (e.g., 'Professor', 'Coordinator', 'Director')", max_length=100)),
                ('context_description', models.TextField(help_text='Describe what this role does and its context')),
                ('is_active', models.BooleanField(default=True, help_text='Only one role per user can be active')),
                ('complexity_level', models.CharField(choices=[('simple', 'Simple - Basic context only'), ('medium', 'Medium - Context + filters + keywords'), ('advanced', 'Advanced - Full customization')], default='simple', max_length=20)),
                ('can_respond_topics', models.TextField(blank=True, help_text='Topics/questions AI can answer (one per line)')),
                ('cannot_respond_topics', models.TextField(blank=True, help_text='Topics AI should escalate to you (one per line)')),
                ('allowed_domains', models.TextField(blank=True, help_text='Email domains to process (e.g., @eafit.edu.co, @company.com)')),
                ('auto_send', models.BooleanField(default=False, help_text='Auto-send responses or require approval for this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Role',
                'verbose_name_plural': 'AI Roles',
                'ordering': ['-is_active', '-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='temporalrule',
            name='ai_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporal_rules', to='gmail_app.airole'),
        ),
    ]
